#!/bin/bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"

SIMULATOR="${REPO_ROOT}/build/bin/Simulator"
CONFIG="${REPO_ROOT}/configs/systolic_ws_256x256_c8_simple_noc_ascend910c_hbm128_ddr5_12ch_768gb.json"
MODELS_LIST_DIR="${REPO_ROOT}/example/trace_tests/baseline_intro_sweep_model_lists"
RESULT_ROOT="${REPO_ROOT}/results/hstu_trace_sweep_runs"

MAX_JOBS="${MAX_JOBS:-30}"
DRY_RUN=0

BASE_LAYERS=8
BASE_HIDDEN=512
BASE_HISTORY_LEN=2048
BASE_MACRO_BATCH_SIZE=512
BASE_USERS_PER_BATCH=2
BASE_NUM_USERS=2
CANDIDATES_PER_USER=10240

LAYERS_LIST=(4 8 12)
HIDDEN_LIST=(256 512 1024)
HISTORY_LEN_LIST=(1024 2048 4096)
MACRO_BATCH_SIZE_LIST=(256 512 1024)
USERS_PER_BATCH_LIST=(1 2 4)
PIPELINE_PRELOAD_LIST=(false true)

usage() {
  cat <<EOF
Usage: $(basename "$0") [--dry-run] [--max-jobs N]

Runs HSTU trace control-variable cases generated by generate_hstu_trace_sweep.sh.

Options:
  --dry-run      Print commands without running Simulator.
  --max-jobs N   Maximum concurrent Simulator processes. Default: ${MAX_JOBS}.
EOF
}

while (($#)); do
  case "$1" in
    --dry-run)
      DRY_RUN=1
      shift
      ;;
    --max-jobs)
      if [[ $# -lt 2 || "$2" == -* ]]; then
        echo "Error: --max-jobs requires a numeric argument" >&2
        exit 1
      fi
      MAX_JOBS="$2"
      shift 2
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      echo "Error: unknown argument $1" >&2
      usage >&2
      exit 1
      ;;
  esac
done

if ! [[ "${MAX_JOBS}" =~ ^[1-9][0-9]*$ ]]; then
  echo "Error: MAX_JOBS must be a positive integer, got ${MAX_JOBS}" >&2
  exit 1
fi

if [[ ! -x "${SIMULATOR}" ]]; then
  echo "Error: Simulator binary not found or not executable: ${SIMULATOR}" >&2
  exit 1
fi

if [[ ! -f "${CONFIG}" ]]; then
  echo "Error: config file not found: ${CONFIG}" >&2
  exit 1
fi

case_name() {
  local layers="$1"
  local hidden="$2"
  local history_len="$3"
  local macro_batch_size="$4"
  local users_per_batch="$5"
  local num_users="$6"

  echo "hstu_l${layers}_h${hidden}_hist${history_len}_cand${CANDIDATES_PER_USER}_mb${macro_batch_size}_u${num_users}_upb${users_per_batch}"
}

add_case() {
  local layers="$1"
  local hidden="$2"
  local history_len="$3"
  local macro_batch_size="$4"
  local users_per_batch="$5"
  local num_users="$6"

  local name
  name="$(case_name "${layers}" "${hidden}" "${history_len}" "${macro_batch_size}" "${users_per_batch}" "${num_users}")"
  if [[ -n "${SEEN_CASES[${name}]:-}" ]]; then
    return
  fi

  SEEN_CASES["${name}"]=1
  CASES+=("${layers},${hidden},${history_len},${macro_batch_size},${users_per_batch},${num_users},${name}")
}

wait_for_slot() {
  while (( $(jobs -pr | wc -l) >= MAX_JOBS )); do
    sleep 1
  done
}

declare -A SEEN_CASES=()
CASES=()
PIDS=()
PID_NAMES=()

add_case \
  "${BASE_LAYERS}" \
  "${BASE_HIDDEN}" \
  "${BASE_HISTORY_LEN}" \
  "${BASE_MACRO_BATCH_SIZE}" \
  "${BASE_USERS_PER_BATCH}" \
  "${BASE_NUM_USERS}"

for layers in "${LAYERS_LIST[@]}"; do
  add_case "${layers}" "${BASE_HIDDEN}" "${BASE_HISTORY_LEN}" "${BASE_MACRO_BATCH_SIZE}" "${BASE_USERS_PER_BATCH}" "${BASE_NUM_USERS}"
done

for hidden in "${HIDDEN_LIST[@]}"; do
  add_case "${BASE_LAYERS}" "${hidden}" "${BASE_HISTORY_LEN}" "${BASE_MACRO_BATCH_SIZE}" "${BASE_USERS_PER_BATCH}" "${BASE_NUM_USERS}"
done

for history_len in "${HISTORY_LEN_LIST[@]}"; do
  add_case "${BASE_LAYERS}" "${BASE_HIDDEN}" "${history_len}" "${BASE_MACRO_BATCH_SIZE}" "${BASE_USERS_PER_BATCH}" "${BASE_NUM_USERS}"
done

for macro_batch_size in "${MACRO_BATCH_SIZE_LIST[@]}"; do
  add_case "${BASE_LAYERS}" "${BASE_HIDDEN}" "${BASE_HISTORY_LEN}" "${macro_batch_size}" "${BASE_USERS_PER_BATCH}" "${BASE_NUM_USERS}"
done

for users_per_batch in "${USERS_PER_BATCH_LIST[@]}"; do
  num_users="${users_per_batch}"
  add_case "${BASE_LAYERS}" "${BASE_HIDDEN}" "${BASE_HISTORY_LEN}" "${BASE_MACRO_BATCH_SIZE}" "${users_per_batch}" "${num_users}"
done

RUN_ID="$(date +"%Y%m%d_%H%M%S")"
RESULT_DIR="${RESULT_ROOT}/${RUN_ID}"

if (( DRY_RUN == 0 )); then
  mkdir -p "${RESULT_DIR}"
fi

total_runs=$((${#CASES[@]} * ${#PIPELINE_PRELOAD_LIST[@]}))
echo "Total cases: ${#CASES[@]}"
echo "Total runs: ${total_runs}"
echo "Max concurrent jobs: ${MAX_JOBS}"
echo "Result directory: ${RESULT_DIR}"

for case_spec in "${CASES[@]}"; do
  IFS=',' read -r layers hidden history_len macro_batch_size users_per_batch num_users name <<< "${case_spec}"
  models_list="${MODELS_LIST_DIR}/${name}_models_list.json"

  if [[ ! -f "${models_list}" ]]; then
    if (( DRY_RUN )); then
      echo "DRY-RUN warning: models_list not found: ${models_list}" >&2
    else
      echo "Error: models_list not found: ${models_list}" >&2
      echo "Run scripts/generate_hstu_trace_sweep.sh first." >&2
      exit 1
    fi
  fi

  for pipeline_preload in "${PIPELINE_PRELOAD_LIST[@]}"; do
    run_name="${name}_pipeline_${pipeline_preload}"
    log_path="${RESULT_DIR}/${run_name}.log"
    report_path="${RESULT_DIR}/${run_name}_memory_report.json"

    cmd=(
      "${SIMULATOR}"
      --config "${CONFIG}"
      --models_list "${models_list}"
      --mode trace
      --log_level info
      --pipeline_preload "${pipeline_preload}"
      --memory_report_json "${report_path}"
    )

    if (( DRY_RUN )); then
      printf 'DRY-RUN %s > %s\n' "${cmd[*]}" "${log_path}"
      continue
    fi

    wait_for_slot
    echo "Launching ${run_name}"
    {
      echo "case=${name}"
      echo "pipeline_preload=${pipeline_preload}"
      echo "layers=${layers}"
      echo "hidden=${hidden}"
      echo "history_len=${history_len}"
      echo "macro_batch_size=${macro_batch_size}"
      echo "num_users=${num_users}"
      echo "users_per_batch=${users_per_batch}"
      echo "models_list=${models_list}"
      echo "memory_report_json=${report_path}"
      echo "command=${cmd[*]}"
      echo
      "${cmd[@]}"
    } > "${log_path}" 2>&1 &
    PIDS+=("$!")
    PID_NAMES+=("${run_name}")
  done
done

if (( DRY_RUN == 0 )); then
  failures=0
  for index in "${!PIDS[@]}"; do
    if ! wait "${PIDS[$index]}"; then
      echo "FAILED: ${PID_NAMES[$index]}" >&2
      failures=$((failures + 1))
    fi
  done
  echo "DONE: logs written to ${RESULT_DIR}"
  if (( failures > 0 )); then
    echo "ERROR: ${failures} case(s) failed" >&2
    exit 1
  fi
fi
